### ISSUE TITLE
Pruebas Adicionales Para Verificar Funcionalidad Básica

### ISSUE THREAD

**Issue by cmonsalvec** [jguilindro/ExGuilindroSum#1]
Estimado Julio Cesar,

Favor asegurarse que las siguientes pruebas funcionan:

Nota: podría ser que la versión de Junit no sea la que está usando, ni los nombres de las clases probadas sean las mismas, entonces primero adaptar las pruebas según su trabajo.

Si termina esto, entonces espero me permita ver por este medio los resultados de las pruebas (captura), y el código correspondiente a las pruebas.

@Test
public void cuandoUnSoloNumeroEsUsadoSeRetornaEseValor() {
Assert.assertEquals(3, Sumador("3"));
}

@Test
public void cuandoDosNumerosSonUsadosEntoncesRetornamosSuSuma() {
Assert.assertEquals(9, Sumador("3,6"));
}

**Comment by jguilindro** [comment]
El problema ha sido resuelto, le adjunto el código fuente de las pruebas y las imágenes confirmando su aprobación:

Prueba de solo un numero (Test1.java):

`import static org.junit.Assert.*;
import org.junit.Rule;
import org.junit.Test;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnit;
import org.mockito.junit.MockitoRule;

public class Test1 {
	@Rule 
	public MockitoRule mockitoRule = MockitoJUnit.rule();
	@Test
	public void test() {
		Suma spySuma= Mockito.spy(Suma.class);
		String s= "3";
		int[] numeros= new int[2];
		numeros[0]= 3;
		numeros[1]= 0;
		Mockito.when((spySuma.convertidor(s))).thenReturn(numeros);
		int esperado= 3;
		int obtenido;
		obtenido= spySuma.sumador(spySuma.convertidor(s));
		assertEquals("Test satisfactorio", esperado,obtenido);
	}

}`

Prueba de dos numeros (Test2.java):

`import static org.junit.Assert.*;
import org.junit.Rule;
import org.junit.Test;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnit;
import org.mockito.junit.MockitoRule;

public class Test2 {
	@Rule 
	public MockitoRule mockitoRule = MockitoJUnit.rule();
	@Test
	public void test() {
		Suma spySuma= Mockito.spy(Suma.class);
		String s= "3,6";
		int[] numeros= new int[2];
		numeros[0]= 3;
		numeros[1]= 6;
		Mockito.when((spySuma.convertidor(s))).thenReturn(numeros);
		int esperado= 9;
		int obtenido;
		obtenido= spySuma.sumador(spySuma.convertidor(s));
		assertEquals("Test satisfactorio", esperado,obtenido);
	}

}`

![prueba 2 numeros](https://cloud.githubusercontent.com/assets/10717191/22701022/749a7170-ed2a-11e6-9365-b399d76b0bf0.png)
![prueba 1 solo numero](https://cloud.githubusercontent.com/assets/10717191/22701023/749ce7c0-ed2a-11e6-8e43-0079206deea2.png)
