### ISSUE TITLE
Deseo Sumar Mas de Dos Números

### ISSUE THREAD

**Issue by cmonsalvec** [jguilindro/ExGuilindroSum#2]
Estimado Julio Cesar,

Deseo que Sumadora pueda sumar más de dos números. Por ejemplo, debería poderse generar una prueba basado en el siguiente Assert:

Assert.assertEquals(3+6+15+18+46+33, Sumadora("3,6,15,18,46,33"));

Nuevamente, puede ser que se deba adaptar el Assert para el proyecto. Igual que antes notificarme por este medio el resultado de la prueba exitosa, y realizar el commit respectivo.

Gracias

**Comment by jguilindro** [comment]
El problema ha sido resuelto, le adjunto el código fuente y las capturas de pantalla.

Prueba para mas de dos numeros (Test3.java):

`import static org.junit.Assert.*;
import org.junit.Rule;
import org.junit.Test;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnit;
import org.mockito.junit.MockitoRule;

public class Test3 {
	@Rule 
	public MockitoRule mockitoRule = MockitoJUnit.rule();
	@Test
	public void test() {
		Suma spySuma= Mockito.spy(Suma.class);
		String s= "3,6,15,18,46,33";
		int[] numeros= new int[6];
		numeros[0]= 3;
		numeros[1]= 6;
		numeros[2]= 15;
		numeros[3]= 18;
		numeros[4]= 46;
		numeros[5]= 33;
		Mockito.when((spySuma.convertidor(s))).thenReturn(numeros);
		int esperado= 3+6+15+18+46+33;
		int obtenido;
		obtenido= spySuma.sumador(spySuma.convertidor(s));
		assertEquals("Test satisfactorio", esperado,obtenido);
	}

}
`

![prueba mas de dos numeros](https://cloud.githubusercontent.com/assets/10717191/22701594/08e8346a-ed2c-11e6-8f62-a4aa0f2aa9fb.png)
