### ISSUE TITLE
Deseo ver Su Estilo de Programación

### ISSUE THREAD

**Issue by cmonsalvec** [jguilindro/ExGuilindroSum#3]
Estimado Julio Cesar,

Vamos bien, pero me preocupa el estilo de programación. Yo espero ver que el estilo sea según las convenciones de codificación de SUN.

Entonces favor enviarme el reporte de Checkstyle del código tal como se encuentra hasta el momento para poder ver como estamos con el estilo de programación. Favor configurar el Checkstyle para que reporte sobre el estilo propuesto por SUN.

**Comment by jguilindro** [comment]
Creados los reportes de checkstyle, se encuentran en la \build\reports\checkstyle del proyecto.
Adjunto imagen del task de gradle

![reporte checkstyle](https://cloud.githubusercontent.com/assets/10717191/22702735/ac0e908c-ed2f-11e6-8cc8-3bbdda934206.png)

**Comment by cmonsalvec** [comment]
Gracias, favor enviarme una captura del reporte generado para ver sus errores de estilo

**Comment by jguilindro** [comment]
Adjunto capturas de dos reportes, uno para el main que sería la clase Suma y otro para los Tests

![reporte checkstyle](https://cloud.githubusercontent.com/assets/10717191/22702906/4b8b4326-ed30-11e6-8c2b-bc226eee78c5.png)
