### ISSUE TITLE
Mejorar las identaciones

### ISSUE THREAD

**Issue by cmonsalvec** [jguilindro/ExGuilindroSum#4]
Estimado Julio César,

Su checkstyle muestra que tiene demasiados errores causados por no hacer un buen uso de las identaciones (sangrías). Favor corregir estos problemas y volver a enviar su checkstyle. No se si se pueda hacer un refactoring en Eclipse para solucionar esto rápidamente.

**Comment by jguilindro** [comment]
Se corrigieron los errores de identaciones en la clase Suma. Se adjunta una foto del reporte actualizado luego de las correcciones.

![reporte identaciones clase suma](https://cloud.githubusercontent.com/assets/10717191/22703564/948b7fbc-ed32-11e6-99e7-e451282c56e2.png)
