### ISSUE TITLE
Mayores a 1000 no deben ser sumados

### ISSUE THREAD

**Issue by cmonsalvec** [jguilindro/ExGuilindroSum#5]
Estimado Julio Cesar,

Deseo que los números mayores a mil sean despreciados, no se sumen. Por ejemplo revisar el siguiente assert:

Assert.assertEquals(3+1000+6, StringCalculator.add("3,1000,1001,6,1234"));

Como notará mi deseo en este caso es que no se sumen ni el 1001 ni el 1234 pues son mayores a 1000.

Esta validación la debe hacer en su programa principal, no en el convertidor.

Gracias

**Comment by jguilindro** [comment]
Se corrigió el problema. Adjunto el código del test4 y la imagen de confirmación que todos los tests se corrieron exitosamente. 

Código de Test4:
`import static org.junit.Assert.*;
import org.junit.Rule;
import org.junit.Test;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnit;
import org.mockito.junit.MockitoRule;

public class Test4 {
	@Rule 
	public MockitoRule mockitoRule = MockitoJUnit.rule();
	@Test
	public void test() {
		Suma spySuma= Mockito.spy(Suma.class);
		String s= "3,1000,1001,6,1234";
		int[] numeros= new int[5];
		numeros[0]= 3;
		numeros[1]= 1000;
		numeros[2]= 1001;
		numeros[3]= 6;
		numeros[4]= 1234;
		Mockito.when((spySuma.convertidor(s))).thenReturn(numeros);
		int esperado= 3+1000+6;
		int obtenido;
		obtenido= spySuma.sumador(spySuma.convertidor(s));
		assertEquals("Test satisfactorio", esperado,obtenido);
	}

}
`

![prueba mayores a mil](https://cloud.githubusercontent.com/assets/10717191/22704006/2b8889a4-ed34-11e6-8c95-74fdcc507144.png)
